kocdigital/Carbon

- Carbon.WebApplication/Carbon.WebApplication.csproj
- Carbon.WebApplication/IServiceCollectionExtensions.cs
AddBearerAuthentication extension method can now retrieve bearer events
> Bearer Authenticator can now be passed some events

- Carbon.WebApplication.SolutionService/Carbon.WebApplication.SolutionService.csproj
- Carbon.WebApplication.SolutionService/Services/SolutionRegistrationService.cs
and
- Some Performance Improvements
> Critical bug fixed for SolutionRegistration when there is no default MassTransit usage

- Carbon.WebApplication.Grpc.Client/Carbon.WebApplication.Grpc.Client.csproj
- Carbon.WebApplication.Grpc/Carbon.WebApplication.Grpc.csproj
- Carbon.WebApplication.Grpc/CarbonGrpcMinimalStartup.cs
- Carbon.WebApplication.Grpc/CarbonGrpcStartup.cs
- Carbon.WebApplication.Grpc/CommonGrpcStartup.cs
Carbon.WebApplication.Grpc
3.0.0-preview
- Dotnet 6 support with minimal and not minimal api added
Carbon.WebApplication.Grpc.Client
2.5.0
- Dotnet 6.0 target framework added
> grpc dotnet 6

- Carbon.MassTransit/AsyncReqResp/Events/IRequestCarrierRequest.cs
- Carbon.MassTransit/AsyncReqResp/Events/IRequestSentFailed.cs
- Carbon.MassTransit/AsyncReqResp/Events/IRequestSentSucceed.cs
- Carbon.MassTransit/AsyncReqResp/Events/IRequestStarterRequest.cs
- Carbon.MassTransit/AsyncReqResp/Events/IResponseCarrier.cs
- Carbon.MassTransit/AsyncReqResp/Events/IResponseFailed.cs
- Carbon.MassTransit/AsyncReqResp/Events/IResponseSucceed.cs
- Carbon.MassTransit/AsyncReqResp/Events/RequestCarrierRequest.cs
- Carbon.MassTransit/AsyncReqResp/Events/RequestSentFailed.cs
- Carbon.MassTransit/AsyncReqResp/Events/RequestSentSucceed.cs
- Carbon.MassTransit/AsyncReqResp/Events/RequestStarterRequest.cs
- Carbon.MassTransit/AsyncReqResp/Events/ResponseCarrier.cs
- Carbon.MassTransit/AsyncReqResp/Events/ResponseFailed.cs
- Carbon.MassTransit/AsyncReqResp/Events/ResponseSucceed.cs
- Carbon.MassTransit/AsyncReqResp/IReqRespBus.cs
- Carbon.MassTransit/AsyncReqResp/RequestHandlerActivity.cs
- Carbon.MassTransit/AsyncReqResp/RequestResponseState.cs
- Carbon.MassTransit/AsyncReqResp/RequestResponseStateMachine.cs
- Carbon.MassTransit/AsyncReqResp/ResponseHandlerActivity.cs
- Carbon.MassTransit/AsyncReqResp/StaticHelpers.cs
- Carbon.MassTransit/Carbon.MassTransit.csproj
- Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
Carbon.MassTransit
3.5.0
- Request-Response Async Pattern introduced
> Request-Response Async Pattern introduced

- Carbon.WebApplication/Carbon.WebApplication.csproj
- Carbon.WebApplication/CarbonMinimalStartup.cs
Carbon 4.0.0 is now in release version.
> full version Carbon 4

- Carbon.WebApplication/Carbon.WebApplication.csproj
> Critical bug fixed for Directory separator char to specific platform

- Carbon.MassTransit/AsyncReqResp/Events/IRequestStarterRequest.cs
- Carbon.MassTransit/AsyncReqResp/Events/IResponder.cs
- Carbon.MassTransit/AsyncReqResp/Events/RequestStarterRequest.cs
- Carbon.MassTransit/AsyncReqResp/Events/Responder.cs
- Carbon.MassTransit/AsyncReqResp/RequestResponseStateMachine.cs
- Carbon.MassTransit/AsyncReqResp/ResponseHandlerActivity.cs
- Carbon.MassTransit/AsyncReqResp/StaticHelpers.cs
- Carbon.MassTransit/Carbon.MassTransit.csproj
- Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
* ReqRespAsync as GetResponse/Respond Pattern introduced
* Awaitable saga, routing slip or ReqRespAsync
* Some other useful extension methods
> ReqRespAsync as GetResponse/Respond Pattern introduced

- Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
- Carbon.Redis/Carbon.Redis.csproj
No impacts are expected as only new methods introduced
> New Redis Extension Methods Added

- Carbon.MassTransit/AsyncReqResp/Events/IResponseFailed.cs
- Carbon.MassTransit/AsyncReqResp/Events/ResponseFailed.cs
- Carbon.MassTransit/AsyncReqResp/StaticHelpers.cs
- Carbon.MassTransit/Carbon.MassTransit.csproj
All response codes other than 200 OK will be assumed as ResponseFailed
> ResponseCode handling bug fix

- Carbon.HttpClient.Auth/README.Md
- Carbon.MassTransit/README.Md
- Carbon.Redis/Abstractions/ICarbonCache.cs
- Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
- Carbon.Redis/Carbon.Redis.csproj
- Carbon.Redis/Extensions/CarbonRedisCache.cs
- Carbon.Redis/Extensions/ICarbonRedisBuilderExtensions.cs
- Carbon.Redis/IRedisSettings.cs
- Carbon.Redis/README.Md
- Carbon.Redis/RedisSettings.cs
- Carbon.Redis/ServiceCollectionExtensions.cs
> Some Redis Extension Methods 

- Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
- Carbon.Redis/Carbon.Redis.csproj
- Carbon.Redis/Extensions/CarbonRedisCache.cs
- Carbon.Redis/Extensions/CarbonRedisCacheOptions.cs
- Carbon.Redis/Extensions/ICarbonRedisBuilderExtensions.cs
- Carbon.Redis/README.md
HashRemove and HashCounter supports added
> Enabling pub/sub is now optional, defaults to false

- Carbon.Redis/Carbon.Redis.csproj
- Carbon.Redis/ServiceCollectionExtensions.cs
Deleted try catch expression(unnecessary and don't preserve stack trace).
Replaced Obsolete method with suggested method.
> Carbon Redis minor refactoring

- Carbon.MassTransit/AsyncReqResp/RequestHandlerActivity.cs
- Carbon.MassTransit/AsyncReqResp/ResponseHandlerActivity.cs
- Carbon.MassTransit/AsyncReqResp/StaticHelpers.cs
- Carbon.MassTransit/Carbon.MassTransit.csproj
- Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
- Carbon.WebApplication.SolutionService/Carbon.WebApplication.SolutionService.csproj
- Carbon.WebApplication.SolutionService/Services/SolutionRegistrationService.cs
Solution Registration servicebus support has been restored as well
> Service Bus support restored for ReqRespAsync

- Carbon.WebApplication.Grpc/Carbon.WebApplication.Grpc.csproj
- Carbon.WebApplication.Grpc/CommonGrpcStartup.cs
- Carbon.WebApplication/Carbon.WebApplication.csproj
- Carbon.WebApplication/CommonStartup.cs
- Cors Policy changes(Location parameter is added to WithExposedHeaders)
> Cors Policy changes(Location parameter is added to WithExposedHeaders)

- Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
- Carbon.Redis/Carbon.Redis.csproj
Redis multi-get async support.
> feat: Redis multi get async support.

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Domain.EntityFrameworkCore.Extensions/EFExtensions.cs
- WhereContains use to AndAlso or OrElse
> fix: WhereContains use to AndAlso or OrElse

- Carbon.PagedList/Carbon.PagedList.csproj
- Carbon.PagedList/PagedList.cs
- Carbon.WebApplication/BaseDtoValidator.cs
- Carbon.WebApplication/Carbon.WebApplication.csproj
- Update IPageableDto validator for assign PageSize 0. When PageSize 0 the datas returns without pagination with development in version 4.5.3.
- Update add item business to PageList when isAllDataRequest is true
> fix: PageList fix for return without pagination.

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Domain.EntityFrameworkCore.Extensions/EFExtensions.cs
This update includes the addition of 'WhereIf' and 'WhereIfContains' extension methods. These methods offer the ability to apply predicate filters to queries based on a specific condition, further enhancing our query capabilities.
> Update Carbon.Domain.EntityFrameworkCore to version 3.2.2

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Domain.EntityFrameworkCore.Extensions/EFExtensions.cs
fix: #18399 TRENSearchAndOrProblem list parameter split problem
> fix: #18399 TRENSearchAndOrProblem list parameter split problem

- Carbon.Domain.Abstractions/Repositories/IRepository.cs
- Carbon.Domain.Abstractions/Repositories/ITenantRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/AllReadWrite/EFRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/AllReadWrite/EFTenantManagedRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/AllReadWrite/EFTenantManagedTenantRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/AllReadWrite/EFTenantRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/WithReadOnly/EFTenantManagedTenantWithReadOnlyRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/WithReadOnly/EFTenantManagedWithReadOnlyRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/WithReadOnly/EFTenantWithReadOnlyRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/WithReadOnly/EFWithReadOnlyRepository.cs
New functions with CancellationToken have been added
> New functions with CancellationToken have been added

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Domain.EntityFrameworkCore.Extensions/EFExtensions.cs
feat: TR-EN Search problem, added Equals method expression by "useTrEnSearch" property.
> feat: TR-EN Search problem, added Equals method expression

- Carbon.Common/Carbon.Common.csproj
- Carbon.Common/Constant/ElasticQueryConstant.cs
- Carbon.ElasticSearch.Abstractions/Carbon.ElasticSearch.Abstractions.csproj
- Carbon.ElasticSearch.Abstractions/IElasticRepository.cs
- Carbon.ElasticSearch/BaseElasticRepository.cs
- Carbon.ElasticSearch/Carbon.ElasticSearch.csproj
feat:DeleteAllAsync method is added IElasticRepository to clear all index data by tenantId
> feat:DeleteAllAsync method is added IElasticRepository to clear all index data by tenantId

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Domain.EntityFrameworkCore.Extensions/EFExtensions.cs
- Carbon.Quartz.Migrate.Context/Carbon.Quartz.Migrate.Context.csproj
- Carbon.Quartz.Migrate.MSSQL/Carbon.Quartz.Migrate.MSSQL.csproj
- Carbon.Quartz.Migrate.PostgreSQL/Carbon.Quartz.Migrate.PostgreSQL.csproj
- Carbon.Quartz/Carbon.Quartz.csproj
- Carbon.WebApplication.EntityFrameworkCore/Carbon.WebApplication.EntityFrameworkCore.csproj
Bump version numbers to reflect updates for .NET 8 support and enhancements
> Fix: Pagination with OrderBy Fixed

- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/AllReadWrite/EFRepository.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/AllReadWrite/EFTenantManagedRepository.cs
findasync method input parameter type edit
> fix: findasync method input parameter type edit

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
input parameter type of the findasync method has been changed.
> fix: input parameter type of the findasync method has been changed.
