- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Quartz.Migrate.Context/Carbon.Quartz.Migrate.Context.csproj
- Carbon.Quartz.Migrate.MSSQL/Carbon.Quartz.Migrate.MSSQL.csproj
- Carbon.Quartz.Migrate.PostgreSQL/Carbon.Quartz.Migrate.PostgreSQL.csproj
- Carbon.Quartz/Carbon.Quartz.csproj
- Carbon.WebApplication.EntityFrameworkCore/Carbon.WebApplication.EntityFrameworkCore.csproj
Carbon.WebApplication.EntityFrameworkCore
2.2.0
Dotnet 6 and EfCore 6 support added when referenced by Carbon.Domain.EntityFrameworkCore 3.0.0 and Dotnet 6.0
Carbon.Domain.EntityFrameworkCore
- 3.0.0
Dotnet 6 and EntityFrameworkCore 6 support added.
All Quartz packages supports the packages listed above (1.2.0)
> Dotnet 6 upgrades for EfCore referenced projects and Efcore 6 support

- Carbon.MassTransit/AsyncReqResp/Events/RequestCarrierRequest.cs
- Carbon.MassTransit/AsyncReqResp/StaticHelpers.cs
- Carbon.MassTransit/Carbon.MassTransit.csproj
- Carbon.Quartz/Carbon.Quartz.csproj
- Carbon.Quartz/IQuartzClusterableService.cs
- Carbon.Quartz/QuartzService.cs
- Carbon.Quartz/QuartzServiceBuilder.cs
Carbon.MassTransit
3.5.2
- Minor fixes
- Request Response Async Pattern responder can respond from anywhere thanks to bus 
Carbon.Quartz
1.3.0
- Job Delete added to service
- QuartzService auto registered when AddQuartzScheduler used
- Scheduler now can be retrieved for purpose of raw Quartz usage instead of QuartzService based usage
> quartz and masstransit improvements

- Carbon.WebApplication.SolutionService/Carbon.WebApplication.SolutionService.csproj
Carbon.Domain.Messages updated from 1.8.0 to 1.9.18 for Solution model Uri prop
> Carbon.Domain.Messages nuget package updated

- Carbon.Redis/Abstractions/CarbonContentSerializationType.cs
- Carbon.Redis/Abstractions/ICarbonCache.cs
- Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
- Carbon.Redis/Abstractions/Serialization.cs
- Carbon.Redis/Carbon.Redis.csproj
- Carbon.Redis/Extensions/CarbonRedisCache.cs
- Carbon.Redis/Extensions/SerializationExtensions.cs
- Carbon.Redis/RedisExtensions.cs
- Carbon.Redis/RedisHelper.cs
- Carbon.Redis/ServiceCollectionExtensions.cs
* Carbon.Redis JSON binary serializer added on the top of binary formatter serializer which is unsupported as of dotnet 5. Simply use static method ICarbonCacheExtensions.SetSerializationType as desired serialization type which defaults to binaryformatter.
* If you try to get binaryformatter serialized keys via json binary serializer from redis, you will receive default value (such as null). At that moment, remove the existing key, and add the new one with the new serializer, or use set to replace it.
* System.Text.Json (faster) is used as master serializer/deserializer replacing Newtonsoft.Json. This may require to add [Serializable] tag over your objects, make sure you consider it!
> Carbon.Redis Serializer Changes

- Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
- Carbon.Redis/Carbon.Redis.csproj
*Numerous type of handy extension methods are added such as Hash, HashAsObject, Set
*Use HashAsObject to store a complete object into hash fields for boosted performance (Only supports Json serialization), and able to get selected fields rather than the entire object
*Use Set for relationships or etc.
> Numerous type of handy extension methods are added

- Carbon.Redis/Carbon.Redis.csproj
- Carbon.Redis/CustomRedisHealthCheck.cs
- Carbon.Redis/DummyConnectionMultiplexer.cs
- Carbon.Redis/DummyRedisServer.cs
- Carbon.Redis/IRedisSettings.cs
- Carbon.Redis/RedisDatabase.cs
- Carbon.Redis/RedisSettings.cs
- Carbon.Redis/Sentinel/ISentinelConnectionMultiplexer.cs
- Carbon.Redis/Sentinel/SentinelConnectionMultiplexer.cs
- Carbon.Redis/ServiceCollectionExtensions.cs
- Multiple nodes of Sentinel and Redis Cluster support (It was buggy previously, even if you could define multiple in config, it was causing an unexpected behaviour)
- More accurate healthcheck for any kind of server installation (Cluster, Sentinel, Basic)
- StackExchange.Redis upgrade
> Multiple Sentinel and Redis Cluster support

- Carbon.MassTransit/Carbon.MassTransit.csproj
- Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
- Carbon.MassTransit/ReceiveEndpointObserver.cs
You can create quorum queues, or migrate your classic queues to quorum queues automatically.
Beware of that, during the migration data loss may occur.
> [Carbon.MassTransit] Quorum Queues introduced

- Carbon.MassTransit/Carbon.MassTransit.csproj
- Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
- It is now possible to supply custom configuration objects to AddRabbitMqBus and AddServiceBus extensions.
- It is now possible to give custom health check tags to AddRabbitMqBus extensions (helps in avoiding duplicates).
> AddRabbitMqBus and AddServiceBus overloads

- Carbon.MassTransit/Carbon.MassTransit.csproj
- Carbon.WebApplication.SolutionService/Carbon.WebApplication.SolutionService.csproj
- MultiTarget framework support (.net3.1 - 5 - 6) rather than being previously single target with .NetStandard 2.0 which is outdated
> MultiTarget framework support (.net3.1 - 5 - 6) (MassTransit and dependent projects)

- Carbon.MassTransit/Carbon.MassTransit.csproj
- Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
- Carbon.MassTransit/RabbitMQReceiveEndpointObserver.cs
- It is now possible to call AddAsHighAvailableQueue and AddAsDefaultQueue extensions using custom RabbitMQSettings objects.
> AddAsHighAvailableQueue custom settings

- Carbon.Common/Carbon.Common.csproj
- Carbon.Common/IQueryableExtensions.cs
This pull request introduces enhancements to the 'OrderBy' method, enabling more robust deep property sorting functionality. The improvements include support for case-insensitive property name lookup and the ability to access properties at multiple levels. With this enhancement, sorting based on complex nested properties becomes more flexible and versatile.
Changes Made:
- Implemented case-insensitive property name lookup for deep sorting.
- Added support for multi-level property access in the sorting process.
> Enhance Deep Property Sorting in OrderBy

- Carbon.Common/Carbon.Common.csproj
- Carbon.Common/IQueryableExtensions.cs
- Carbon.ConsoleApplication.Extensions/Carbon.ConsoleApplication.csproj
- Carbon.Domain.Abstractions/Carbon.Domain.Abstractions.csproj
- Carbon.ElasticSearch.Abstractions/Carbon.ElasticSearch.Abstractions.csproj
- Carbon.ElasticSearch/Carbon.ElasticSearch.csproj
- Carbon.HttpClient.Auth/Carbon.HttpClient.Auth.csproj
- Carbon.HttpClient/Carbon.HttpClient.csproj
- Carbon.PagedList.Mapster/Carbon.PagedList.Mapster.csproj
- Carbon.TimeSeriesDb.Abstractions/Carbon.TimeSeriesDb.Abstractions.csproj
- Carbon.WebApplication/Carbon.WebApplication.csproj
This pull request resolves a scenario in the `OrderBy` method where a `propInfo` that is `null` leads to the creation of an unintended lambda expression `(x => x)`. This PR introduces a solution to bypass the creation of the lambda expression when `propInfo` is `null`, ensuring that only valid property sorting expressions are generated.
Changes Made:
- Added a null check for propInfo within the inner loop. 
- Skipped the creation of the lambda expression if propInfo is null. 
- Improved code clarity and maintainability.
> Fix: Handle Null PropInfo in OrderBy Method

- Carbon.WebApplication/Carbon.WebApplication.csproj
- Carbon.WebApplication/TenantManagementHandler/ControllerAttributes/OwnershipFilter.cs
We are now sending solutionId as null when checking endpoint permissions. This way we can also check if the related permission is coming from a solution other than the solution that actually sent the main request
>  OwnershipFilter check now disregards any solution id header

- Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
- Carbon.Redis/Carbon.Redis.csproj
- Carbon.Redis/Extensions/SerializationExtensions.cs
Keys can be fetched in both binary and json formatter serialized, but can only be set in json formatter serialized to transform binary formatter serialized keys which is unsupported.
> TryAlternativeDeserialization method added

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Domain.EntityFrameworkCore.Extensions/EFExtensions.cs
- Carbon.WebApplication.EntityFrameworkCore/Carbon.WebApplication.EntityFrameworkCore.csproj
Refactor ownership filtering logic; include 'OwnerType.None' in conditions for more comprehensive permission assessment.
Currently, an entity registered as OwnerType=None is not seen by any user assigned a role. The purpose of this change is to make the entity registered as None visible to everyone.
> feat: add ownertype none in ownership filters

- Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
- Carbon.Redis/Carbon.Redis.csproj
- Carbon.Redis/CustomRedisHealthCheck.cs
- Carbon.Redis/DummyConnectionMultiplexer.cs
- Carbon.Redis/DummyRedisServer.cs
- Carbon.Redis/Extensions/CarbonRedisCache.cs
- Carbon.Redis/Extensions/ICarbonRedisBuilderExtensions.cs
- Carbon.Redis/IRedisSettings.cs
- Carbon.Redis/RedisDatabase.cs
- Carbon.Redis/RedisSettings.cs
- Carbon.Redis/ServiceCollectionExtensions.cs
- Carbon.WebApplication.Grpc/Carbon.WebApplication.Grpc.csproj
- Carbon.WebApplication.Grpc/CommonGrpcStartup.cs
- Carbon.WebApplication/Carbon.WebApplication.csproj
- Carbon.WebApplication/CommonStartup.cs
Redis sentinel implemented correctly and degraded health check state added.
In sentinel mode, slaves becomes read-only (Generally Preferred Way) and master writes are async; so you should not write to master and try to read from slave.
> Redis Sentinel Fixes

- Carbon.Common/BaseRequestPageDto.cs
- Carbon.Common/Carbon.Common.csproj
- Carbon.Common/Extensions/StringExtensions.cs
- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.Domain.EntityFrameworkCore.Extensions/EFExtensions.cs
- Carbon.WebApplication/Carbon.WebApplication.csproj
Currently, in services using Carbon, the same codes were written over and over again to make the includes for solution migration and call the tolist method. An additional extension method has been added to shorten them. In this method, the necessary includes for owner and solution are added and the tolist extension method is called. For the same method, a alternative that will work with pagenation was also written. 
In addition, a method that makes tolist for pagination has been added. In the get all methods in the services, pagination operations were performed repeatedly. This method can be used to minimise these.
- Added new extension method to EFExtensions (ToListEntityFilteredWithIncludeAsync, ToPagedListEntityFilteredWithIncludeAsync, ToPagedListEntityAsync)
- Added …
> feat: Add new methods to EFExtensions

- Carbon.Domain.Abstractions/Carbon.Domain.Abstractions.csproj
- Carbon.Domain.Abstractions/Entities/IEntity.cs
- Carbon.Domain.Abstractions/Entities/IGenericKeyEntity.cs
An IEntity object, which can be parameterized for the purpose of transforming Primary Id columns found in the product roadmap into Long, has been added.
> Feature/2484578/0/entity UUID to long conversion

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- Carbon.PagedList.EntityFrameworkCore/Carbon.PagedList.EntityFrameworkCore.csproj
- Carbon.PagedList.EntityFrameworkCore/PagedListExtensions.cs
- Carbon.PagedList.Mapster/Carbon.PagedList.Mapster.csproj
- Carbon.PagedList/BasePagedList.cs
- Carbon.PagedList/Carbon.PagedList.csproj
- Carbon.PagedList/PagedList.cs
- Carbon.WebApplication.EntityFrameworkCore/Carbon.WebApplication.EntityFrameworkCore.csproj
- Carbon.WebApplication/Carbon.WebApplication.csproj
- tests/Carbon.PagedList.EntityFrameworkCore.UnitTests/DataShares/QueryableExtensionsDataShare.cs
- tests/Carbon.PagedList.EntityFrameworkCore.UnitTests/PagedListExtensionsTest.cs
- tests/Carbon.PagedList.UnitTests/BasePagedListTests.cs
- tests/Carbon.PagedList.UnitTests/PagedListTests.cs
- tests/Carbon.WebApplication.UnitTests/BaseDtoValidatorTests.cs
- The pageSize and pageNumber validations have been deleted from the constructor method in the PagedList and BasePagedList classes in the Carbon.PagedList package.
- Updated version for packages using the Carbon.PagedList package.
- Removed unit test methods about pageSize and pageNumber count.
> fix: Carbon.PagedList validation error

- Carbon.Domain.EntityFrameworkCore.Extensions/EFExtensions.cs
Changelog:
- WhereContains method's searchByWords property business changed
- The operation of the "searchByWords" variable has been modified so that all searched words are present at the sametime in each record.
> feat: TREN Search or expression changed to and

- Carbon.Domain.EntityFrameworkCore.Extensions/Carbon.Domain.EntityFrameworkCore.csproj
- WhereContains method's searchByWords property business changed
- The operation of the "searchByWords" variable has been modified so that all searched words are present at the sametime in each record.
> feat: WhereContains method's searchByWords property business changed

- Carbon.Domain.EntityFrameworkCore.Extensions/Repositories/AllReadWrite/EFRepository.cs
- tests/Carbon.Domain.EntityFrameworkCore.UnitTests/EFRepositoryTest.cs
Cancellation token eklendikten sonra hata veren FindAsync fonksiyonları aşağıdaki konuya uygun güncellendi .
https://github.com/dotnet/efcore/issues/22667
> feat:findasync object type param edited

- Carbon.ExceptionHandling/Carbon.ExceptionHandling.Abstractions.csproj
- Carbon.ExceptionHandling/CarbonException.cs
- Carbon.WebApplication/Carbon.WebApplication.csproj
- Carbon.WebApplication/HttpGlobalExceptionFilter.cs
Added a property named overrideMessageAndCode to the CarbonException class. The default value of this property is set to true. In the constructor of CarbonException, check this property to determine whether the message and code are overridden or not.
> Carbon exception message override improvements.
